USE mentari_db;

INSERT IGNORE INTO specializations (name, slug, description, icon) VALUES
('Anestesi', 'anestesi', 'Pelayanan anestesi & perawatan intensif perioperatif', 'anastesi.svg'),
('Pediatri / Anak', 'pediatri', 'Kesehatan bayi, anak & remaja', 'baby.svg'),
('Bedah Anak', 'bedah-anak', 'Tindakan bedah khusus untuk pasien anak', 'bedah anak.svg'),
('Bedah Ortopedi', 'bedah-ortopedi', 'Bedah tulang, persendian & cedera muskuloskeletal', 'bedah ortopedi.svg'),
('Bedah Plastik', 'bedah-plastik', 'Rekonstruksi & estetik jaringan tubuh', 'bedah pelastik.svg'),
('Bedah Saraf', 'bedah-saraf', 'Bedah otak, tulang belakang & sistem saraf perifer', 'bedah saraf.svg'),
('Bedah Umum', 'bedah-umum', 'Tindakan bedah organ umum & emergensi', 'bedah umum.svg'),
('Kardiologi', 'kardiologi', 'Diagnostik & terapi penyakit jantung', 'cardiology.svg'),
('Kardiovaskular', 'kardiovaskular', 'Gangguan pembuluh darah & sistem vaskular', 'kardiovaskular.svg'),
('Gigi / Kedokteran Gigi', 'kedokteran-gigi', 'Perawatan kesehatan gigi & mulut', 'dentistry.svg'),
('Dermatologi', 'dermatologi', 'Kulit, rambut & kuku', 'dermatology.svg'),
('Endokrinologi', 'endokrinologi', 'Gangguan hormon & metabolisme', 'Endokrinologi.svg'),
('Gastroenterologi', 'gastroenterologi', 'Saluran cerna, hati & pankreas', 'Gastroenterologi.svg'),
('Nefrologi', 'nefrologi', 'Penyakit ginjal & gangguan fungsi ginjal', 'Nefrologi.svg'),
('Pulmonologi', 'pulmonologi', 'Penyakit paru & pernapasan', 'Pulmonologi.svg'),
('Urologi', 'urologi', 'Saluran kemih & sistem reproduksi pria', 'Urologi.svg'),
('Farmasi Klinik', 'farmasi', 'Manajemen terapi obat & informasi farmasi', 'farmasi.svg'),
('Fisioterapi', 'fisioterapi', 'Rehabilitasi fungsi gerak & fisik', 'fisioterapi.svg'),
('Rehabilitasi Klinik', 'rehabilitasi-klinik', 'Pemulihan pasca cedera & kondisi kronis', 'rehabilitas klinik.svg'),
('Geriatri', 'geriatri', 'Kesehatan usia lanjut terpadu', 'geriatri.svg'),
('Ginekologi', 'ginekologi', 'Kesehatan reproduksi wanita', 'ginekologi.svg'),
('Obstetri & Ginekologi', 'obstetri-ginekologi', 'Kehamilan, persalinan & reproduksi', 'gynecology.svg'),
('Gizi Klinik', 'gizi-klinik', 'Terapi nutrisi medis & dietetik', 'gizi klinik.svg'),
('Hematologi', 'hematologi', 'Gangguan darah & pembekuan', 'hematologi.svg'),
('Imunologi & Alergi', 'imunologi-alergi', 'Gangguan imun & reaksi alergi', 'imun&alergi.svg'),
('Penyakit Infeksi', 'penyakit-infeksi', 'Infeksi bakteri, virus & tropis', 'infeksi.svg'),
('Laktasi', 'laktasi', 'Konsultasi menyusui & manajemen ASI', 'laktasi.svg'),
('Mata / Oftalmologi', 'mata', 'Pemeriksaan & tindakan kesehatan mata', 'mata.svg'),
('Neurologi', 'neurologi', 'Gangguan otak, saraf & neuromuskular', 'neurologi.svg'),
('Onkologi', 'onkologi', 'Deteksi & terapi kanker terpadu', 'ongkologi.svg'),
('Perawatan Paliatif', 'perawatan-paliatif', 'Pendampingan nyeri & kualitas hidup pasien terminal', 'paliatif.svg'),
('Patologi Klinik', 'patologi-klinik', 'Analisa laboratorium diagnostik', 'patologi klinik.svg'),
('Perinatologi', 'perinatologi', 'Perawatan bayi baru lahir berisiko', 'perinatologi.svg'),
('Psikiatri', 'psikiatri', 'Kesehatan jiwa & gangguan psikiatrik', 'psikiatri.svg'),
('Psikologi Klinis', 'psikologi-klinis', 'Evaluasi & terapi psikologis klinis', 'psikologi klinis.svg'),
('Radiologi', 'radiologi', 'Pencitraan medis diagnostik & intervensi', 'radiologi.svg'),
('Reumatologi', 'reumatologi', 'Penyakit autoimun & sendi', 'reumatologi.svg'),
('THT (Otolaringologi)', 'tht', 'Telinga, hidung, tenggorok & terkait', 'tht.svg'),
('Perawatan Luka', 'perawatan-luka', 'Manajemen luka akut & kronis', 'woundcare.svg'),
('Kesehatan Tulang', 'kesehatan-tulang', 'Pencegahan & perawatan kesehatan tulang', 'bone.svg');